#Rupees converter
print("Rupees converter")
rupees =  int(input("Enter the amount in Indian rupees \n"))
#1 Indian Rupee = 0.012 US Dollar
print(f"{rupees} Indian rupees = "+str(rupees*0.012)+" US Dollar")
#1.00 Indian Rupee = 0.000521763829517 Silver Ounces
print(f"{rupees} Indian rupees = "+str(rupees*0.000521763829517)+" Silver Ounces")
#1 Indian Rupee = 0.00000018 Bitcoin
print(f"{rupees} Indian rupees = "+str(rupees*0.00000018)+" Bitcoin")
#1 Indian Rupee = 0.060 Brazilian Real
print(f"{rupees} Indian rupees = "+str(rupees*0.060)+" Brazilian Real")
#1 Indian Rupee =0.016 Canadian Dollar
print(f"{rupees} Indian rupees = "+str(rupees*0.016)+" Canadian Dollar")
#1 Indian Rupee =0.018 Australian Dollar
print(f"{rupees} Indian rupees = "+str(rupees*0.018)+" Australian Dollar")
#1 Indian Rupee = 1.14 Albanian Lek
print(f"{rupees} Indian rupees = "+str(rupees*1.14)+" Albanian Lek")
#1 Indian Rupee = 10.25 Argentine Peso
print(f"{rupees} Indian rupees = "+str(rupees*10.25)+" Argentine Peso")
#1 Indian Rupee =1.32 Bangladeshi Taka
print(f"{rupees} Indian rupees = "+str(rupees*1.32)+" Bangladeshi Taka")
#1 Indian Rupee = 0.012 Bermudian Dollar
print(f"{rupees} Indian rupees = "+str(rupees*0.012)+" Bermudian Dollar")
#1 Indian Rupee = 0.024 Barbadian Dollar
print(f"{rupees} Indian rupees = "+str(rupees*0.024)+" Barbadian Dollar")
#1 Indian Rupee = 0.021 Aruban Florin
print(f"{rupees} Indian rupees = "+str(rupees*0.021)+" Aruban Florin")
#1 Indian Rupee = 0.083 Bolivian Boliviano
print(f"{rupees} Indian rupees = "+str(rupees*0.083)+" Bolivian Boliviano")
#1 Indian Rupee = 34.33 Burundian Franc
print(f"{rupees} Indian rupees = "+str(rupees*34.33)+" Burundian Franc")
#1 Indian Rupee = 0.024 Belize Dollar
print(f"{rupees} Indian rupees = "+str(rupees*0.024)+" Belize Dollar")
#1 Indian Rupee = 0.022 Bulgarian Lev
print(f"{rupees} Indian rupees = "+str(rupees*0.022)+" Bulgarian Lev")
#1 Indian Rupee = 0.16 Botswana Pula
print(f"{rupees} Indian rupees = "+str(rupees*0.16)+" Botswana Pula")
#1 Indian Rupee = 5.44 Comorian Franc
print(f"{rupees} Indian rupees = "+str(rupees*5.44)+" Comorian Franc")
#1 Indian Rupee =1.79 Japanese Yen
print(f"{rupees} Indian rupees = "+str(rupees*1.79)+" Japanese Yen")