#Mind Palace Maker
print("Kindly Press enter to continue")
input()
print("The mind palace itself is something you create in your mind.")
input()
print("Let's say you pick your childhood home as your mind palace.")
input()
print("Remember, this is your mind palace,")
input()
print("so personalize it! Make it a place you enjoy revisiting in your mind.")
input()
print("Let's say,..")
input()
print("You pick your childhood home as your mind palace.")
input()
print("Your route might start at the front door,")
input()
print("then move to the living room with the fireplace,")
input()
print("then to the kitchen with the big window")
input()
print("Are you enjoying..")
input()
print("Next stop is the kitchen table")
input()
print("As you walk through your mind palace in your imagination, stop at specific points that stand out.")
input()
print("These will be your loci,")
input()
print("Loci can be anything from a peculiar doorknob to a creaky floorboard")
input()
print("a specific painting on the wall")
input()
print("or even a particular piece of furniture.")
input()
print("You can continue adding loci throughout your house")
input()
print("including your bedroom,")
input()
print("bathroom,")
input()
print("or even the backyard.")
input()
print("Feel free to get creative and personalize your mind palace to best suit your preferences.")
input()
print("Remember all things...")
input()
print("Front Door: A talking mailbox that shouts greetings.")
input()
print("Living Room Couch: A giant, fluffy panda bear wearing sunglasses.")
input()
print("Kitchen Table: A disco ball raining down colorful lights.")
input()
print("Remember, this is your mind palace, so get creative and have fun with it!")
input()
print(" you've constructed the basic framework of your new mind palace")
input()
print("You can now populate it with information you want to remember by associating it with the specific landmarks you've chosen.")
input()
print("Very nice memories....:)")
input()